### ISSUE TITLE
Unable to import Pedprops.

### ISSUE THREAD

**Issue by Sentryandreas** [LendoK/Blender_GTA_V_model_importer#1]
Unlike the weapon props and ragdolls, I can't import the pedprops (Hats, Glasses, etc.) with this error reports. Any solution please?
btw, I'm really enjoying your stuff! Keep up the good works. :D
![bandicam 2020-04-19 22-18-41-367](https://user-images.githubusercontent.com/59036487/79688989-02f79100-828d-11ea-9946-d5befdddc6de.jpg)

**Comment by LendoK** [comment]
Can you tell me the model name please. I will try to reproduce it.

**Comment by Sentryandreas** [comment]
It's for every propmodels btw, but I tried "s_m_y_hwaycop_01_p" props on that one.
more exactly, I tried to import "p_head_000_high" in that file.

**Comment by LendoK** [comment]
Fixed with  bb0f616
