### ISSUE TITLE
Error When Trying To Enable Add-On

### ISSUE THREAD

**Issue by mrdgmedia** [LendoK/Blender_GTA_V_model_importer#12]
Hello, I have a Blander error.  It shows me this....

![Blender Error](https://user-images.githubusercontent.com/17502792/94225380-5fa14c80-feba-11ea-839e-e30183d0c622.png)

Any idea how to resolve this?

**Comment by Tosyk** [comment]
well, it's never mentioned, but I think your blender version doesn't met the requirements:
https://github.com/LendoK/Blender_GTA_V_model_importer/blob/master/__init__.py

wrong version! use 2.80+ instead

**Comment by mrdgmedia** [comment]
> well, it's never mentioned, but I think your blender version doesn't met the requirements:
> https://github.com/LendoK/Blender_GTA_V_model_importer/blob/master/__init__.py
> 
> wrong version! use 2.80+ instead

Thanks for that.  I will try it.

**Comment by LendoK** [comment]
Yes, you need at least Blender version 2.80 to run this add-on
