### ISSUE TITLE
posibility of load ODD/ODR instead of mesh

### ISSUE THREAD

**Issue by Tosyk** [LendoK/Blender_GTA_V_model_importer#3]
is it possible to load ODD/ODR instead of mesh?
in these reference files all the info about what to load.

it will also resolve the issue with multiple skeletons for each bodypart
here's example: [ig_amandatownley.zip](https://github.com/LendoK/Blender_GTA_V_model_importer/files/4525678/ig_amandatownley.zip)

**Comment by LendoK** [comment]
Do you mean to import the whole folder?
Create all meshes and skeleton from this folder, create materials, assign textures to it, etc.?
A one click import for a Character?
Is it possible to export complete Characters/folders from Open V?

**Comment by Tosyk** [comment]
Yes, openIV allows to export full set of models/textures for a single character.
And yes, something like one click to load all that is in ODD file but at very least meshes + textures. Load materials and textures could be an extra feature

**Comment by LendoK** [comment]
@Tosyk now you can import meshes and armatures by ODD and ODR files. The rework is not completely done, but you can already test it on this branch "file_parser". The problem with the skeleton in the ig_amandatownley example is tricky, because only the head part has a reference to the skeleton. For all the other parts I have to find the armature by guessing, I couldn't find a better solution.

**Comment by Tosyk** [comment]
@LendoK thank you! working great! I'll test it more with different models.
![image](https://user-images.githubusercontent.com/24209966/80740694-20e0b380-8b21-11ea-9259-a0b95385a132.png)
The problem with the skeleton may not be tricky if you load head first — all further models will use loaded skeleton from head folder.
found that all the meshes shows weird vertex normal behavior when rotate bones:
![image](https://user-images.githubusercontent.com/24209966/80741012-a1071900-8b21-11ea-83f3-ffd3082abddf.png)
also - maybe it's important for you - in order to properly use normal map Green channel need to be negated. Here's my example:
![image](https://user-images.githubusercontent.com/24209966/80741221-f6432a80-8b21-11ea-9c5e-078caab8f8b9.png)

**Comment by LendoK** [comment]
Thanks for testing! I will add the inverted green channel of the normal map to the generated material. Does the texture import work for you?
The weird custom normals behavior probably comes from way how Blender calculates the tangents. Maybe it's not recalculated after the bone transformation.

**Comment by Tosyk** [comment]
> Any idea how the specular map can be used with the Principled BSDF Shader?
here's my settings for skin shader for example:
![image](https://user-images.githubusercontent.com/24209966/80757581-061c3800-8b3d-11ea-9ea1-745097029e5b.png)

and here's settings for cloth:
![image](https://user-images.githubusercontent.com/24209966/80760157-22ba6f00-8b41-11ea-9a54-bfa57b54d40b.png)

> Does the texture import work for you?
only normal map is importing, but not the specular map. Also diffuse textures are in separate files with YTD extension - they need to be exported separately into separate folder and almost always there's several diffuse textures so I don't think there's a way to automatically assign diffuse textures with addon :/

Also I think that models have second UV channel. I see diffuse maps of hairs have different uv:
![image](https://user-images.githubusercontent.com/24209966/80760358-71680900-8b41-11ea-8d5d-fb382ede9331.png)

this what can be achieved with some manipulations:
![image](https://user-images.githubusercontent.com/24209966/80760936-5c3faa00-8b42-11ea-99bc-8b7a95ef727e.png)

**Comment by LendoK** [comment]
> Also I think that models have second UV channel. I see diffuse maps of hairs have different uv:

I can not see any second UV channel in the vertex data:

> 0.06347657 -0.08544922 0.68750000 / 0.00000000 0.00000000 1.00000000 0.00000000 / 0 0 76 0 / 0.44140630 -0.84765630 -0.29687500 / 232 115 0 255 / 0 0 0 0 / **0.78169250 0.16419980** / -0.56389760 -0.51866280 0.64265740 1.00000000

There is only one Vec2.

Seems like the first submesh is some kind of LOD, or mask. The second submesh looks fine.
![screenshot](https://user-images.githubusercontent.com/37044454/80792332-81f59f00-8b94-11ea-8c00-aadcd528061c.png)

**Comment by LendoK** [comment]
changes ar now on master

**Comment by Tosyk** [comment]
btw, instead of this complicated and redundant construction with mix shader:
![image](https://user-images.githubusercontent.com/24209966/81117350-9ab4da80-8f2f-11ea-8f52-6886d6802414.png)

you can use simple this:
![image](https://user-images.githubusercontent.com/24209966/81117385-abfde700-8f2f-11ea-8043-15dc789764fe.png)
