### ISSUE TITLE
Specific meshes not exporting with armature

### ISSUE THREAD

**Issue by Nipeno** [LendoK/Blender_GTA_V_model_importer#5]
I tried importing
update\x64\dlcpacks\mpchristmas2018\dlc.rpf\x64\models\cdimages\mpchristmas2018_male.rpf\mp_m_freemode_01_mp_m_christmas2018\berd_000_u.ydd
but it had no rig. i also tried exporting the other parts of that model but none of them had the rig.

**Comment by LendoK** [comment]
Yes, seems like there is no .skel file exported from OpenIV for any of the parts. Usually the .skel is in the head part, but for this model there is no head.

**Comment by Tosyk** [comment]
multiplayer character models could use shared a single head model file with morphs that makes it different
