### ISSUE TITLE
please fix vertex normals

### ISSUE THREAD

**Issue by Tosyk** [LendoK/Blender_GTA_V_model_importer#8]
I notice that all the meshes shows weird vertex normal behavior when rotate bones:
![image](https://user-images.githubusercontent.com/24209966/81119751-16b12180-8f34-11ea-9e5f-2bac75948dc0.png)
would be great if you can fix this

if it's important I can show you this:
![image](https://user-images.githubusercontent.com/24209966/81120371-40b71380-8f35-11ea-84ba-0a761821cc6d.png)

**Comment by LendoK** [comment]
Custom normals don't work with armature deformation.
![Bildschirmfoto von 2020-05-06 17-44-45](https://user-images.githubusercontent.com/37044454/81198371-b072e000-8fc1-11ea-90f3-361a22d69674.png)

You have to remove the custom normals.
![Bildschirmfoto von 2020-05-06 17-44-56](https://user-images.githubusercontent.com/37044454/81198447-c7b1cd80-8fc1-11ea-85a1-d832cbb924db.png)
Check all the Store options. And then Clear Custom Split Normals.
Turn off auto smooth
![Bildschirmfoto von 2020-05-06 17-49-40](https://user-images.githubusercontent.com/37044454/81198652-09427880-8fc2-11ea-99d4-34c75c43cc59.png)
Then use Object -> Shade Smooth and in edit mode remove the doubles with "Merge by Distance"

Result:
![Bildschirmfoto von 2020-05-06 17-45-26](https://user-images.githubusercontent.com/37044454/81198958-5f172080-8fc2-11ea-9820-b325057d644d.png)
